version: "3"
services:
  front:
    build: ./client
    ports:
      - 8080:3000
    command: yarn run start
    volumes:
      - ./client/src/:/app/src
    networks:
      - mynetwork
networks:
  mynetwork:
